package raid24contribution.sc_model.expressions;

import org.w3c.dom.Node;

/**
 * Usually this expression is used to replace another expression which cannot be transformed the way
 * it is. This expression is never generated by parsing an AST but can be inserted afterwards by
 * modeltransformers.
 * 
 * 
 */
public class EmptyExpression extends MarkerExpression {
    
    private static final long serialVersionUID = 82354679746467508L;
    
    public EmptyExpression(Node n) {
        super(n);
    }
    
    @Override
    public String toString() {
        return "";
    }
    
}
